FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM pierrezemb/gostatic
COPY --from=builder /app/dist/ /srv/http/
CMD ["-port","8080","-https-promote", "-enable-logging"]
